# Generated by Django 4.2.3 on 2023-07-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('other_companies', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='perfumers/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='perfumists',
        ),
        migrations.DeleteModel(
            name='Perfumist',
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfumers',
            field=models.ManyToManyField(to='scents.perfumer'),
        ),
    ]
