# Generated by Django 4.2.3 on 2023-07-14 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0003_alter_perfumeaccord_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('top', 'Top'), ('mid', 'Mid'), ('bot', 'Bot')], default='top', max_length=3)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scents.note')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scents.perfume')),
            ],
            options={
                'db_table': 'perfume_note',
            },
        ),
    ]
