# Generated by Django 4.2.3 on 2023-07-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0004_perfumenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='desginer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scents.designer'),
        ),
    ]
