# Generated by Django 4.2.3 on 2023-07-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0005_alter_perfume_desginer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='desginer',
            new_name='designer',
        ),
    ]
