# Generated by Django 4.2.3 on 2023-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0007_alter_perfumeaccord_table_alter_perfumenote_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumenote',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('mid', 'Mid'), ('bot', 'Bot'), ('plain', 'Plain')], default='top', max_length=5),
        ),
    ]
