# Generated by Django 4.2.3 on 2023-07-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scents', '0009_alter_perfumenote_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='website',
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='perfumes/groups/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='perfumes/groups/banners/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scents.family')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='perfume',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scents.family'),
        ),
    ]
